options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nca-toolkit-project-446011/no-code-architects-toolkit:$COMMIT_SHA', '.']

images:
- 'gcr.io/nca-toolkit-project-446011/no-code-architects-toolkit:$COMMIT_SHA'
