options:
  logging: GCS_ONLY  # Use Cloud Storage for logging
  logsBucket: 'gs://nca-toolkit-bucket-ghf'  # Specify your logs bucket

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
